// <auto-generated />
using System;
using MegaDesk_Razor_Pages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaDeskRazorPages.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250301215728_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MegaDesk_Razor_Pages.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeskDepth")
                        .HasColumnType("int");

                    b.Property<string>("DeskMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeskWidth")
                        .HasColumnType("int");

                    b.Property<int>("NumDrawers")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuoteTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RushOrderDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "John Doe",
                            DeskDepth = 30,
                            DeskMaterial = "Oak",
                            DeskWidth = 60,
                            NumDrawers = 2,
                            QuoteDate = new DateTime(2025, 3, 1, 14, 57, 28, 51, DateTimeKind.Local).AddTicks(4534),
                            QuoteTotal = 1200m,
                            RushOrderDays = 3
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Jane Smith",
                            DeskDepth = 36,
                            DeskMaterial = "Laminate",
                            DeskWidth = 72,
                            NumDrawers = 4,
                            QuoteDate = new DateTime(2025, 3, 1, 14, 57, 28, 51, DateTimeKind.Local).AddTicks(4539),
                            QuoteTotal = 1500m,
                            RushOrderDays = 5
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Alice Johnson",
                            DeskDepth = 24,
                            DeskMaterial = "Pine",
                            DeskWidth = 48,
                            NumDrawers = 3,
                            QuoteDate = new DateTime(2025, 2, 28, 14, 57, 28, 51, DateTimeKind.Local).AddTicks(4542),
                            QuoteTotal = 1100m,
                            RushOrderDays = 7
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Bob Brown",
                            DeskDepth = 30,
                            DeskMaterial = "Veneer",
                            DeskWidth = 60,
                            NumDrawers = 2,
                            QuoteDate = new DateTime(2025, 2, 27, 14, 57, 28, 51, DateTimeKind.Local).AddTicks(4547),
                            QuoteTotal = 1000m,
                            RushOrderDays = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
